# Generated by Django 5.1.2 on 2025-04-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('learning_style_V', models.BooleanField(default=False)),
                ('learning_style_A', models.BooleanField(default=False)),
                ('learning_style_R', models.BooleanField(default=False)),
                ('learning_style_K', models.BooleanField(default=False)),
                ('age_group_kid', models.BooleanField(default=False)),
                ('age_group_young', models.BooleanField(default=False)),
                ('age_group_student', models.BooleanField(default=False)),
                ('age_group_adult', models.BooleanField(default=False)),
                ('age_group_mature', models.BooleanField(default=False)),
            ],
        ),
    ]
