# Generated by Django 5.1.2 on 2025-04-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='age_group_adult',
            field=models.BooleanField(default=False, verbose_name='Взрослые'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='age_group_kid',
            field=models.BooleanField(default=False, verbose_name='Дети'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='age_group_mature',
            field=models.BooleanField(default=False, verbose_name='Зрелые'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='age_group_student',
            field=models.BooleanField(default=False, verbose_name='Студенты'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='age_group_young',
            field=models.BooleanField(default=False, verbose_name='Подростки'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='learning_style_A',
            field=models.BooleanField(default=False, verbose_name='Аудиал'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='learning_style_K',
            field=models.BooleanField(default=False, verbose_name='Кинестетик'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='learning_style_R',
            field=models.BooleanField(default=False, verbose_name='Читатель/писатель'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='learning_style_V',
            field=models.BooleanField(default=False, verbose_name='Визуал'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
