# Generated by Django 5.1.2 on 2025-04-20 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_percent', models.FloatField(blank=True, null=True, verbose_name='Визуал')),
                ('audio_percent', models.FloatField(blank=True, null=True, verbose_name='Аудиал')),
                ('reader_percent', models.FloatField(blank=True, null=True, verbose_name='Читатель-писатель')),
                ('kinesthetic_percent', models.FloatField(blank=True, null=True, verbose_name='Кинестетик')),
                ('primary_style', models.CharField(blank=True, max_length=50, null=True, verbose_name='Основной стиль обучения')),
                ('secondary_style', models.CharField(blank=True, max_length=50, null=True, verbose_name='Второстепенный стиль обучения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
