# Generated by Django 5.1.2 on 2024-11-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('article', models.TextField()),
            ],
            options={
                'db_table': 'lessons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpeakingTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('question_1', models.TextField()),
                ('question_2', models.TextField()),
                ('question_3', models.TextField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('theme', models.TextField()),
                ('article', models.TextField()),
                ('question_1', models.TextField()),
                ('question_2', models.TextField()),
                ('question_3', models.TextField()),
                ('question_4', models.TextField()),
                ('question_5', models.TextField()),
                ('translate_1', models.TextField()),
                ('translate_2', models.TextField()),
                ('translate_3', models.TextField()),
                ('translate_4', models.TextField()),
                ('translate_5', models.TextField()),
            ],
            options={
                'db_table': 'topics',
                'managed': True,
            },
        ),
    ]
