# Generated by Django 5.1.2 on 2024-11-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_english', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('question_1', models.TextField()),
                ('question_2', models.TextField()),
                ('question_3', models.TextField()),
            ],
            options={
                'managed': True,
            },
        ),
    ]
