# Generated by Django 5.1.2 on 2024-12-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_english', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.TextField()),
                ('second_form', models.TextField()),
                ('third_form', models.TextField()),
                ('translate', models.TextField()),
            ],
            options={
                'managed': True,
            },
        ),
    ]
