# Generated by Django 5.1.2 on 2024-12-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_english', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
